import {GAME_CONSTANTS} from './constants'

// Константы для создания линий
export const LINE_CONSTANTS = {
  HORIZONTAL: {
    LENGTH: GAME_CONSTANTS.CELL_SIZE,
    CLICKABLE: {
      VERTICAL_TOLERANCE: GAME_CONSTANTS.CLICK_TOLERANCE.HORIZONTAL.VERTICAL_TOLERANCE,
      HORIZONTAL_PADDING: GAME_CONSTANTS.CLICK_TOLERANCE.HORIZONTAL.HORIZONTAL_PADDING
    }
  },
  VERTICAL: {
    LENGTH: GAME_CONSTANTS.CELL_SIZE,
    CLICKABLE: {
      HORIZONTAL_TOLERANCE: GAME_CONSTANTS.CLICK_TOLERANCE.VERTICAL.HORIZONTAL_TOLERANCE,
      VERTICAL_PADDING: GAME_CONSTANTS.CLICK_TOLERANCE.VERTICAL.VERTICAL_PADDING
    }
  }
} as const

// Константы для граничных линий
export const BORDER_LINES = {
  TOP: 2,
  BOTTOM: 326, // 2 + 9 * 36
  LEFT: 2,
  RIGHT: 326
} as const

// Настройки сетки
export const GRID_CONSTANTS = {
  ROWS: GAME_CONSTANTS.GRID_SIZE,
  COLS: GAME_CONSTANTS.GRID_SIZE,
  HORIZONTAL_LINE_COUNT: 10 * 9, // 10 рядов по 9 линий
  VERTICAL_LINE_COUNT: 9 * 10    // 9 рядов по 10 линий
} as const
