export enum EMessageType {
  PLAYER_JOINED = 'PLAYER_JOINED',
  PLAYER_LEFT = 'PLAYER_LEFT',
  GAME_STATE_UPDATE = 'GAME_STATE_UPDATE',
  LINE_SELECTED = 'LINE_SELECTED',
  CELL_COMPLETED = 'CELL_COMPLETED',
  GAME_STARTED = 'GAME_STARTED',
  GAME_FINISHED = 'GAME_FINISHED',
  PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  ERROR = 'ERROR'
}

export enum EGameStatus {
  WAITING = 'WAITING',
  IN_PROGRESS = 'IN_PROGRESS',
  FINISHED = 'FINISHED'
}
